/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Category from './Category';
import CategoryPath from './CategoryPath';
import GeoJsonPoint from './GeoJsonPoint';

/**
 * The AuctionSimplifiedResponse model module.
 * @module model/AuctionSimplifiedResponse
 * @version v0
 */
class AuctionSimplifiedResponse {
    /**
     * Constructs a new <code>AuctionSimplifiedResponse</code>.
     * @alias module:model/AuctionSimplifiedResponse
     * @param id {String} 
     * @param name {String} 
     * @param category {module:model/Category} 
     * @param categoryPath {module:model/CategoryPath} 
     * @param price {Number} 
     * @param thumbnail {Blob} 
     * @param cityName {String} 
     * @param location {module:model/GeoJsonPoint} 
     */
    constructor(id, name, category, categoryPath, price, thumbnail, cityName, location) { 
        
        AuctionSimplifiedResponse.initialize(this, id, name, category, categoryPath, price, thumbnail, cityName, location);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, category, categoryPath, price, thumbnail, cityName, location) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['category'] = category;
        obj['categoryPath'] = categoryPath;
        obj['price'] = price;
        obj['thumbnail'] = thumbnail;
        obj['cityName'] = cityName;
        obj['location'] = location;
    }

    /**
     * Constructs a <code>AuctionSimplifiedResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuctionSimplifiedResponse} obj Optional instance to populate.
     * @return {module:model/AuctionSimplifiedResponse} The populated <code>AuctionSimplifiedResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuctionSimplifiedResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = Category.constructFromObject(data['category']);
            }
            if (data.hasOwnProperty('categoryPath')) {
                obj['categoryPath'] = CategoryPath.constructFromObject(data['categoryPath']);
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('thumbnail')) {
                obj['thumbnail'] = ApiClient.convertToType(data['thumbnail'], 'Blob');
            }
            if (data.hasOwnProperty('cityName')) {
                obj['cityName'] = ApiClient.convertToType(data['cityName'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = GeoJsonPoint.constructFromObject(data['location']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuctionSimplifiedResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuctionSimplifiedResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuctionSimplifiedResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `category`
        if (data['category']) { // data not null
          Category.validateJSON(data['category']);
        }
        // validate the optional field `categoryPath`
        if (data['categoryPath']) { // data not null
          CategoryPath.validateJSON(data['categoryPath']);
        }
        // ensure the json data is a string
        if (data['cityName'] && !(typeof data['cityName'] === 'string' || data['cityName'] instanceof String)) {
            throw new Error("Expected the field `cityName` to be a primitive type in the JSON string but got " + data['cityName']);
        }
        // validate the optional field `location`
        if (data['location']) { // data not null
          GeoJsonPoint.validateJSON(data['location']);
        }

        return true;
    }


}

AuctionSimplifiedResponse.RequiredProperties = ["id", "name", "category", "categoryPath", "price", "thumbnail", "cityName", "location"];

/**
 * @member {String} id
 */
AuctionSimplifiedResponse.prototype['id'] = undefined;

/**
 * @member {String} name
 */
AuctionSimplifiedResponse.prototype['name'] = undefined;

/**
 * @member {module:model/Category} category
 */
AuctionSimplifiedResponse.prototype['category'] = undefined;

/**
 * @member {module:model/CategoryPath} categoryPath
 */
AuctionSimplifiedResponse.prototype['categoryPath'] = undefined;

/**
 * @member {Number} price
 */
AuctionSimplifiedResponse.prototype['price'] = undefined;

/**
 * @member {Blob} thumbnail
 */
AuctionSimplifiedResponse.prototype['thumbnail'] = undefined;

/**
 * @member {String} cityName
 */
AuctionSimplifiedResponse.prototype['cityName'] = undefined;

/**
 * @member {module:model/GeoJsonPoint} location
 */
AuctionSimplifiedResponse.prototype['location'] = undefined;






export default AuctionSimplifiedResponse;

