/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CategoryCreateRequest model module.
 * @module model/CategoryCreateRequest
 * @version v0
 */
class CategoryCreateRequest {
    /**
     * Constructs a new <code>CategoryCreateRequest</code>.
     * @alias module:model/CategoryCreateRequest
     * @param name {String} 
     * @param description {String} 
     * @param isTopLevel {Boolean} 
     * @param isFinalNode {Boolean} 
     */
    constructor(name, description, isTopLevel, isFinalNode) { 
        
        CategoryCreateRequest.initialize(this, name, description, isTopLevel, isFinalNode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, description, isTopLevel, isFinalNode) { 
        obj['name'] = name;
        obj['description'] = description;
        obj['isTopLevel'] = isTopLevel;
        obj['isFinalNode'] = isFinalNode;
    }

    /**
     * Constructs a <code>CategoryCreateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CategoryCreateRequest} obj Optional instance to populate.
     * @return {module:model/CategoryCreateRequest} The populated <code>CategoryCreateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategoryCreateRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('parentCategoryId')) {
                obj['parentCategoryId'] = ApiClient.convertToType(data['parentCategoryId'], 'String');
            }
            if (data.hasOwnProperty('isTopLevel')) {
                obj['isTopLevel'] = ApiClient.convertToType(data['isTopLevel'], 'Boolean');
            }
            if (data.hasOwnProperty('isFinalNode')) {
                obj['isFinalNode'] = ApiClient.convertToType(data['isFinalNode'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CategoryCreateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CategoryCreateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CategoryCreateRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['parentCategoryId'] && !(typeof data['parentCategoryId'] === 'string' || data['parentCategoryId'] instanceof String)) {
            throw new Error("Expected the field `parentCategoryId` to be a primitive type in the JSON string but got " + data['parentCategoryId']);
        }

        return true;
    }


}

CategoryCreateRequest.RequiredProperties = ["name", "description", "isTopLevel", "isFinalNode"];

/**
 * @member {String} name
 */
CategoryCreateRequest.prototype['name'] = undefined;

/**
 * @member {String} description
 */
CategoryCreateRequest.prototype['description'] = undefined;

/**
 * @member {String} parentCategoryId
 */
CategoryCreateRequest.prototype['parentCategoryId'] = undefined;

/**
 * @member {Boolean} isTopLevel
 */
CategoryCreateRequest.prototype['isTopLevel'] = undefined;

/**
 * @member {Boolean} isFinalNode
 */
CategoryCreateRequest.prototype['isFinalNode'] = undefined;






export default CategoryCreateRequest;

