/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Category from './Category';

/**
 * The CategoryPath model module.
 * @module model/CategoryPath
 * @version v0
 */
class CategoryPath {
    /**
     * Constructs a new <code>CategoryPath</code>.
     * @alias module:model/CategoryPath
     * @param pathElements {Array.<module:model/Category>} 
     */
    constructor(pathElements) { 
        
        CategoryPath.initialize(this, pathElements);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pathElements) { 
        obj['pathElements'] = pathElements;
    }

    /**
     * Constructs a <code>CategoryPath</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CategoryPath} obj Optional instance to populate.
     * @return {module:model/CategoryPath} The populated <code>CategoryPath</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategoryPath();

            if (data.hasOwnProperty('pathElements')) {
                obj['pathElements'] = ApiClient.convertToType(data['pathElements'], [Category]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CategoryPath</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CategoryPath</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CategoryPath.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['pathElements']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['pathElements'])) {
                throw new Error("Expected the field `pathElements` to be an array in the JSON data but got " + data['pathElements']);
            }
            // validate the optional field `pathElements` (array)
            for (const item of data['pathElements']) {
                Category.validateJSON(item);
            };
        }

        return true;
    }


}

CategoryPath.RequiredProperties = ["pathElements"];

/**
 * @member {Array.<module:model/Category>} pathElements
 */
CategoryPath.prototype['pathElements'] = undefined;






export default CategoryPath;

