/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SubcategoryResponse from './SubcategoryResponse';

/**
 * The CategoryResponse model module.
 * @module model/CategoryResponse
 * @version v0
 */
class CategoryResponse {
    /**
     * Constructs a new <code>CategoryResponse</code>.
     * @alias module:model/CategoryResponse
     * @param id {String} 
     * @param name {String} 
     * @param isTopLevel {Boolean} 
     * @param description {String} 
     * @param subcategories {Array.<module:model/SubcategoryResponse>} 
     * @param isFinalNode {Boolean} 
     */
    constructor(id, name, isTopLevel, description, subcategories, isFinalNode) { 
        
        CategoryResponse.initialize(this, id, name, isTopLevel, description, subcategories, isFinalNode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name, isTopLevel, description, subcategories, isFinalNode) { 
        obj['id'] = id;
        obj['name'] = name;
        obj['isTopLevel'] = isTopLevel;
        obj['description'] = description;
        obj['subcategories'] = subcategories;
        obj['isFinalNode'] = isFinalNode;
    }

    /**
     * Constructs a <code>CategoryResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CategoryResponse} obj Optional instance to populate.
     * @return {module:model/CategoryResponse} The populated <code>CategoryResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CategoryResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('isTopLevel')) {
                obj['isTopLevel'] = ApiClient.convertToType(data['isTopLevel'], 'Boolean');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('subcategories')) {
                obj['subcategories'] = ApiClient.convertToType(data['subcategories'], [SubcategoryResponse]);
            }
            if (data.hasOwnProperty('isFinalNode')) {
                obj['isFinalNode'] = ApiClient.convertToType(data['isFinalNode'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CategoryResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CategoryResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CategoryResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        if (data['subcategories']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['subcategories'])) {
                throw new Error("Expected the field `subcategories` to be an array in the JSON data but got " + data['subcategories']);
            }
            // validate the optional field `subcategories` (array)
            for (const item of data['subcategories']) {
                SubcategoryResponse.validateJSON(item);
            };
        }

        return true;
    }


}

CategoryResponse.RequiredProperties = ["id", "name", "isTopLevel", "description", "subcategories", "isFinalNode"];

/**
 * @member {String} id
 */
CategoryResponse.prototype['id'] = undefined;

/**
 * @member {String} name
 */
CategoryResponse.prototype['name'] = undefined;

/**
 * @member {Boolean} isTopLevel
 */
CategoryResponse.prototype['isTopLevel'] = undefined;

/**
 * @member {String} description
 */
CategoryResponse.prototype['description'] = undefined;

/**
 * @member {Array.<module:model/SubcategoryResponse>} subcategories
 */
CategoryResponse.prototype['subcategories'] = undefined;

/**
 * @member {Boolean} isFinalNode
 */
CategoryResponse.prototype['isFinalNode'] = undefined;






export default CategoryResponse;

