/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CitySimplifiedResponse from './CitySimplifiedResponse';

/**
 * The PagedCities model module.
 * @module model/PagedCities
 * @version v0
 */
class PagedCities {
    /**
     * Constructs a new <code>PagedCities</code>.
     * @alias module:model/PagedCities
     * @param cities {Array.<module:model/CitySimplifiedResponse>} 
     * @param pageNumber {Number} 
     * @param pageCount {Number} 
     */
    constructor(cities, pageNumber, pageCount) { 
        
        PagedCities.initialize(this, cities, pageNumber, pageCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cities, pageNumber, pageCount) { 
        obj['cities'] = cities;
        obj['pageNumber'] = pageNumber;
        obj['pageCount'] = pageCount;
    }

    /**
     * Constructs a <code>PagedCities</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PagedCities} obj Optional instance to populate.
     * @return {module:model/PagedCities} The populated <code>PagedCities</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PagedCities();

            if (data.hasOwnProperty('cities')) {
                obj['cities'] = ApiClient.convertToType(data['cities'], [CitySimplifiedResponse]);
            }
            if (data.hasOwnProperty('pageNumber')) {
                obj['pageNumber'] = ApiClient.convertToType(data['pageNumber'], 'Number');
            }
            if (data.hasOwnProperty('pageCount')) {
                obj['pageCount'] = ApiClient.convertToType(data['pageCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PagedCities</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PagedCities</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PagedCities.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['cities']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['cities'])) {
                throw new Error("Expected the field `cities` to be an array in the JSON data but got " + data['cities']);
            }
            // validate the optional field `cities` (array)
            for (const item of data['cities']) {
                CitySimplifiedResponse.validateJSON(item);
            };
        }

        return true;
    }


}

PagedCities.RequiredProperties = ["cities", "pageNumber", "pageCount"];

/**
 * @member {Array.<module:model/CitySimplifiedResponse>} cities
 */
PagedCities.prototype['cities'] = undefined;

/**
 * @member {Number} pageNumber
 */
PagedCities.prototype['pageNumber'] = undefined;

/**
 * @member {Number} pageCount
 */
PagedCities.prototype['pageCount'] = undefined;






export default PagedCities;

