/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuctionSimplifiedResponse from './AuctionSimplifiedResponse';

/**
 * The PagedAuctions model module.
 * @module model/PagedAuctions
 * @version v0
 */
class PagedAuctions {
    /**
     * Constructs a new <code>PagedAuctions</code>.
     * @alias module:model/PagedAuctions
     * @param auctions {Array.<module:model/AuctionSimplifiedResponse>} 
     * @param pageNumber {Number} 
     * @param pageCount {Number} 
     */
    constructor(auctions, pageNumber, pageCount) { 
        
        PagedAuctions.initialize(this, auctions, pageNumber, pageCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, auctions, pageNumber, pageCount) { 
        obj['auctions'] = auctions;
        obj['pageNumber'] = pageNumber;
        obj['pageCount'] = pageCount;
    }

    /**
     * Constructs a <code>PagedAuctions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PagedAuctions} obj Optional instance to populate.
     * @return {module:model/PagedAuctions} The populated <code>PagedAuctions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PagedAuctions();

            if (data.hasOwnProperty('auctions')) {
                obj['auctions'] = ApiClient.convertToType(data['auctions'], [AuctionSimplifiedResponse]);
            }
            if (data.hasOwnProperty('pageNumber')) {
                obj['pageNumber'] = ApiClient.convertToType(data['pageNumber'], 'Number');
            }
            if (data.hasOwnProperty('pageCount')) {
                obj['pageCount'] = ApiClient.convertToType(data['pageCount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PagedAuctions</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PagedAuctions</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PagedAuctions.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['auctions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['auctions'])) {
                throw new Error("Expected the field `auctions` to be an array in the JSON data but got " + data['auctions']);
            }
            // validate the optional field `auctions` (array)
            for (const item of data['auctions']) {
                AuctionSimplifiedResponse.validateJSON(item);
            };
        }

        return true;
    }


}

PagedAuctions.RequiredProperties = ["auctions", "pageNumber", "pageCount"];

/**
 * @member {Array.<module:model/AuctionSimplifiedResponse>} auctions
 */
PagedAuctions.prototype['auctions'] = undefined;

/**
 * @member {Number} pageNumber
 */
PagedAuctions.prototype['pageNumber'] = undefined;

/**
 * @member {Number} pageCount
 */
PagedAuctions.prototype['pageCount'] = undefined;






export default PagedAuctions;

