/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuctionDetailedResponse from './model/AuctionDetailedResponse';
import AuctionImagesResponse from './model/AuctionImagesResponse';
import AuctionSimplifiedResponse from './model/AuctionSimplifiedResponse';
import Category from './model/Category';
import CategoryCreateRequest from './model/CategoryCreateRequest';
import CategoryNameResponse from './model/CategoryNameResponse';
import CategoryPath from './model/CategoryPath';
import CategoryPathResponse from './model/CategoryPathResponse';
import CategoryResponse from './model/CategoryResponse';
import CategorySearchResponse from './model/CategorySearchResponse';
import CitySimplifiedResponse from './model/CitySimplifiedResponse';
import CreateAuctionRequest from './model/CreateAuctionRequest';
import GeoJsonPoint from './model/GeoJsonPoint';
import ImageDetailedResponse from './model/ImageDetailedResponse';
import PagedAuctions from './model/PagedAuctions';
import PagedCities from './model/PagedCities';
import SimpleCategoryResponse from './model/SimpleCategoryResponse';
import SubcategoryResponse from './model/SubcategoryResponse';
import UpdateAuctionRequest from './model/UpdateAuctionRequest';
import AuctionCrudControllerApi from './api/AuctionCrudControllerApi';
import AuctionOperationsControllerApi from './api/AuctionOperationsControllerApi';
import CategoryControllerApi from './api/CategoryControllerApi';
import CityOperationsControllerApi from './api/CityOperationsControllerApi';
import ImageControllerApi from './api/ImageControllerApi';
import LoggedInAuctioneerControllerApi from './api/LoggedInAuctioneerControllerApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiDefinition = require('index'); // See note below*.
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiDefinition.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiDefinition.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuctionDetailedResponse model constructor.
     * @property {module:model/AuctionDetailedResponse}
     */
    AuctionDetailedResponse,

    /**
     * The AuctionImagesResponse model constructor.
     * @property {module:model/AuctionImagesResponse}
     */
    AuctionImagesResponse,

    /**
     * The AuctionSimplifiedResponse model constructor.
     * @property {module:model/AuctionSimplifiedResponse}
     */
    AuctionSimplifiedResponse,

    /**
     * The Category model constructor.
     * @property {module:model/Category}
     */
    Category,

    /**
     * The CategoryCreateRequest model constructor.
     * @property {module:model/CategoryCreateRequest}
     */
    CategoryCreateRequest,

    /**
     * The CategoryNameResponse model constructor.
     * @property {module:model/CategoryNameResponse}
     */
    CategoryNameResponse,

    /**
     * The CategoryPath model constructor.
     * @property {module:model/CategoryPath}
     */
    CategoryPath,

    /**
     * The CategoryPathResponse model constructor.
     * @property {module:model/CategoryPathResponse}
     */
    CategoryPathResponse,

    /**
     * The CategoryResponse model constructor.
     * @property {module:model/CategoryResponse}
     */
    CategoryResponse,

    /**
     * The CategorySearchResponse model constructor.
     * @property {module:model/CategorySearchResponse}
     */
    CategorySearchResponse,

    /**
     * The CitySimplifiedResponse model constructor.
     * @property {module:model/CitySimplifiedResponse}
     */
    CitySimplifiedResponse,

    /**
     * The CreateAuctionRequest model constructor.
     * @property {module:model/CreateAuctionRequest}
     */
    CreateAuctionRequest,

    /**
     * The GeoJsonPoint model constructor.
     * @property {module:model/GeoJsonPoint}
     */
    GeoJsonPoint,

    /**
     * The ImageDetailedResponse model constructor.
     * @property {module:model/ImageDetailedResponse}
     */
    ImageDetailedResponse,

    /**
     * The PagedAuctions model constructor.
     * @property {module:model/PagedAuctions}
     */
    PagedAuctions,

    /**
     * The PagedCities model constructor.
     * @property {module:model/PagedCities}
     */
    PagedCities,

    /**
     * The SimpleCategoryResponse model constructor.
     * @property {module:model/SimpleCategoryResponse}
     */
    SimpleCategoryResponse,

    /**
     * The SubcategoryResponse model constructor.
     * @property {module:model/SubcategoryResponse}
     */
    SubcategoryResponse,

    /**
     * The UpdateAuctionRequest model constructor.
     * @property {module:model/UpdateAuctionRequest}
     */
    UpdateAuctionRequest,

    /**
    * The AuctionCrudControllerApi service constructor.
    * @property {module:api/AuctionCrudControllerApi}
    */
    AuctionCrudControllerApi,

    /**
    * The AuctionOperationsControllerApi service constructor.
    * @property {module:api/AuctionOperationsControllerApi}
    */
    AuctionOperationsControllerApi,

    /**
    * The CategoryControllerApi service constructor.
    * @property {module:api/CategoryControllerApi}
    */
    CategoryControllerApi,

    /**
    * The CityOperationsControllerApi service constructor.
    * @property {module:api/CityOperationsControllerApi}
    */
    CityOperationsControllerApi,

    /**
    * The ImageControllerApi service constructor.
    * @property {module:api/ImageControllerApi}
    */
    ImageControllerApi,

    /**
    * The LoggedInAuctioneerControllerApi service constructor.
    * @property {module:api/LoggedInAuctioneerControllerApi}
    */
    LoggedInAuctioneerControllerApi
};
