/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.AuctionCrudControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuctionCrudControllerApi', function() {
    describe('addAuction', function() {
      it('should call addAuction successfully', function(done) {
        //uncomment below and update the code to test addAuction
        //instance.addAuction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('changeCategory', function() {
      it('should call changeCategory successfully', function(done) {
        //uncomment below and update the code to test changeCategory
        //instance.changeCategory(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAuction', function() {
      it('should call deleteAuction successfully', function(done) {
        //uncomment below and update the code to test deleteAuction
        //instance.deleteAuction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAuction', function() {
      it('should call getAuction successfully', function(done) {
        //uncomment below and update the code to test getAuction
        //instance.getAuction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAuctions', function() {
      it('should call getAuctions successfully', function(done) {
        //uncomment below and update the code to test getAuctions
        //instance.getAuctions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchAuctions', function() {
      it('should call searchAuctions successfully', function(done) {
        //uncomment below and update the code to test searchAuctions
        //instance.searchAuctions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAuction', function() {
      it('should call updateAuction successfully', function(done) {
        //uncomment below and update the code to test updateAuction
        //instance.updateAuction(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
