/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.LoggedInAuctioneerControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LoggedInAuctioneerControllerApi', function() {
    describe('getActiveAuctions', function() {
      it('should call getActiveAuctions successfully', function(done) {
        //uncomment below and update the code to test getActiveAuctions
        //instance.getActiveAuctions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getArchivedAuctions', function() {
      it('should call getArchivedAuctions successfully', function(done) {
        //uncomment below and update the code to test getArchivedAuctions
        //instance.getArchivedAuctions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAwaitingAuctions', function() {
      it('should call getAwaitingAuctions successfully', function(done) {
        //uncomment below and update the code to test getAwaitingAuctions
        //instance.getAwaitingAuctions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getExpiredAuctions', function() {
      it('should call getExpiredAuctions successfully', function(done) {
        //uncomment below and update the code to test getExpiredAuctions
        //instance.getExpiredAuctions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRejectedAuctions', function() {
      it('should call getRejectedAuctions successfully', function(done) {
        //uncomment below and update the code to test getRejectedAuctions
        //instance.getRejectedAuctions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
