/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.ImageDetailedResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ImageDetailedResponse', function() {
    it('should create an instance of ImageDetailedResponse', function() {
      // uncomment below and update the code to test ImageDetailedResponse
      //var instance = new OpenApiDefinition.ImageDetailedResponse();
      //expect(instance).to.be.a(OpenApiDefinition.ImageDetailedResponse);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new OpenApiDefinition.ImageDetailedResponse();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new OpenApiDefinition.ImageDetailedResponse();
      //expect(instance).to.be();
    });

    it('should have the property size (base name: "size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new OpenApiDefinition.ImageDetailedResponse();
      //expect(instance).to.be();
    });

    it('should have the property auctionId (base name: "auctionId")', function() {
      // uncomment below and update the code to test the property auctionId
      //var instance = new OpenApiDefinition.ImageDetailedResponse();
      //expect(instance).to.be();
    });

    it('should have the property binaryData (base name: "binaryData")', function() {
      // uncomment below and update the code to test the property binaryData
      //var instance = new OpenApiDefinition.ImageDetailedResponse();
      //expect(instance).to.be();
    });

  });

}));
